using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.WebSockets;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Script.Serialization;
using System.Windows;
using System.Windows.Automation;

enum VoiceState { Idle, Starting, Listening, Finalizing, Delivering, Cancelled, Error }

sealed class VoiceOptions {
 public string Backend="flash",ApiKey="",AppKey="",AccessKey="",ResourceId="volc.bigasr.auc_turbo",Endpoint="https://openspeech.bytedance.com/api/v3/auc/bigmodel/recognize/flash";
 public bool HoldMode,SaveHistory=true;public int RetentionDays=30,MaxSeconds=300;public uint Modifiers=HotkeyGesture.Control|HotkeyGesture.Alt;public int VirtualKey=0x20;
 public bool Ready {get{return (!string.IsNullOrWhiteSpace(ApiKey)||(!string.IsNullOrWhiteSpace(AppKey)&&!string.IsNullOrWhiteSpace(AccessKey)))&&!string.IsNullOrWhiteSpace(ResourceId);}}
 public HotkeyGesture Gesture {get{return new HotkeyGesture(Modifiers,VirtualKey);}}
}

sealed class VoiceTerm {public string word="";public List<string> aliases=new List<string>();public bool enabled=true;public string source="manual";public string createdAt="",updatedAt="";}
sealed class VoiceHistoryItem {public string id="",createdAt="",text="",status="final";}
sealed class VoiceBackup {public int schemaVersion=1;public List<VoiceTerm> terms=new List<VoiceTerm>();}

static class VoiceData {
 static readonly JavaScriptSerializer Json=new JavaScriptSerializer{MaxJsonLength=4*1024*1024};
 public static string Root {get{return Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"BanaStudio");}}
 static string LegacyRoot {get{return Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Banarec");}}
 public static void EnsureMigrated(){Directory.CreateDirectory(Root);string marker=Path.Combine(Root,".migrated-v3");if(File.Exists(marker))return;foreach(string name in new[]{"settings.ini"}){string old=Path.Combine(LegacyRoot,name),now=Path.Combine(Root,name);if(File.Exists(old)&&!File.Exists(now))File.Copy(old,now);}File.WriteAllText(marker,DateTime.UtcNow.ToString("o"),Encoding.UTF8);}
 static string Protect(string value){if(string.IsNullOrEmpty(value))return "";return Convert.ToBase64String(ProtectedData.Protect(Encoding.UTF8.GetBytes(value),null,DataProtectionScope.CurrentUser));}
 static string Unprotect(string value){if(string.IsNullOrEmpty(value))return "";try{return Encoding.UTF8.GetString(ProtectedData.Unprotect(Convert.FromBase64String(value),null,DataProtectionScope.CurrentUser));}catch{return "";}}
 public static VoiceOptions LoadOptions(){EnsureMigrated();string p=Path.Combine(Root,"voice-settings.json");try{var map=Json.Deserialize<Dictionary<string,object>>(File.ReadAllText(p,Encoding.UTF8));var o=new VoiceOptions();o.Backend=Get(map,"backend",o.Backend);o.ApiKey=Unprotect(Get(map,"apiKey"));o.AppKey=Unprotect(Get(map,"appKey"));o.AccessKey=Unprotect(Get(map,"accessKey"));o.ResourceId=Get(map,"resourceId",o.ResourceId);o.Endpoint=Get(map,"endpoint",o.Endpoint);o.HoldMode=Bool(map,"holdMode");o.SaveHistory=!map.ContainsKey("saveHistory")||Bool(map,"saveHistory");o.RetentionDays=Int(map,"retentionDays",30);o.MaxSeconds=Int(map,"maxSeconds",300);o.Modifiers=(uint)Int(map,"modifiers",(int)o.Modifiers);o.VirtualKey=Int(map,"virtualKey",o.VirtualKey);return o;}catch{return new VoiceOptions();}}
 public static void SaveOptions(VoiceOptions o){EnsureMigrated();var map=new Dictionary<string,object>{{"schemaVersion",1},{"backend",o.Backend},{"apiKey",Protect(o.ApiKey)},{"appKey",Protect(o.AppKey)},{"accessKey",Protect(o.AccessKey)},{"resourceId",o.ResourceId},{"endpoint",o.Endpoint},{"holdMode",o.HoldMode},{"saveHistory",o.SaveHistory},{"retentionDays",o.RetentionDays},{"maxSeconds",o.MaxSeconds},{"modifiers",o.Modifiers},{"virtualKey",o.VirtualKey}};Atomic(Path.Combine(Root,"voice-settings.json"),Json.Serialize(map));}
 static string Get(Dictionary<string,object> m,string k,string d=""){object v;return m.TryGetValue(k,out v)&&v!=null?Convert.ToString(v):d;}static bool Bool(Dictionary<string,object> m,string k){object v;return m.TryGetValue(k,out v)&&Convert.ToBoolean(v);}static int Int(Dictionary<string,object> m,string k,int d){object v;int n;return m.TryGetValue(k,out v)&&int.TryParse(Convert.ToString(v),out n)?n:d;}
 public static List<VoiceTerm> LoadTerms(){EnsureMigrated();try{var b=Json.Deserialize<VoiceBackup>(File.ReadAllText(Path.Combine(Root,"dictionary.json"),Encoding.UTF8));return b!=null&&b.terms!=null?b.terms:new List<VoiceTerm>();}catch{return new List<VoiceTerm>();}}
 public static void SaveTerms(IEnumerable<VoiceTerm> terms){Atomic(Path.Combine(Root,"dictionary.json"),Json.Serialize(new VoiceBackup{terms=terms.ToList()}));}
 public static List<VoiceHistoryItem> LoadHistory(){EnsureMigrated();try{return Json.Deserialize<List<VoiceHistoryItem>>(File.ReadAllText(Path.Combine(Root,"history.json"),Encoding.UTF8))??new List<VoiceHistoryItem>();}catch{return new List<VoiceHistoryItem>();}}
 public static void AddHistory(string text,string status,VoiceOptions options){if(!options.SaveHistory||string.IsNullOrWhiteSpace(text))return;var all=LoadHistory();DateTime cutoff=DateTime.UtcNow.AddDays(-Math.Max(1,options.RetentionDays));all=all.Where(x=>{DateTime d;return DateTime.TryParse(x.createdAt,out d)&&d>=cutoff;}).Take(499).ToList();all.Insert(0,new VoiceHistoryItem{id=Guid.NewGuid().ToString("N"),createdAt=DateTime.UtcNow.ToString("o"),text=text,status=status});Atomic(Path.Combine(Root,"history.json"),Json.Serialize(all));}
 public static void ClearHistory(){Atomic(Path.Combine(Root,"history.json"),"[]");}
 public static void ExportJson(string path,IEnumerable<VoiceTerm> terms){File.WriteAllText(path,Json.Serialize(new VoiceBackup{terms=terms.ToList()}),new UTF8Encoding(false));}
 public static List<VoiceTerm> Import(string path){var file=new FileInfo(path);if(!file.Exists)throw new FileNotFoundException("词库文件不存在。",path);if(file.Length>4*1024*1024)throw new InvalidDataException("词库文件不能超过 4 MB。");string ext=Path.GetExtension(path).ToLowerInvariant(),data=File.ReadAllText(path,Encoding.UTF8);List<VoiceTerm> found;if(ext==".json"){var shape=Json.DeserializeObject(data) as Dictionary<string,object>;if(shape==null||!shape.ContainsKey("terms"))throw new InvalidDataException("词库 JSON 缺少 terms。");var b=Json.Deserialize<VoiceBackup>(data);if(b==null||b.schemaVersion!=1||b.terms==null)throw new InvalidDataException("不支持的词库 JSON 格式。");found=b.terms;}else if(ext==".txt")found=data.Split(new[]{"\r\n","\n"},StringSplitOptions.None).Select(x=>NewTerm(x.Trim(),new List<string>(),"import")).ToList();else if(ext==".csv")found=ParseCsv(data);else throw new InvalidDataException("仅支持 JSON、CSV 或 TXT。");return Validate(found);}
 static List<VoiceTerm> ParseCsv(string s){var rows=new List<List<string>>();var row=new List<string>();var cell=new StringBuilder();bool quote=false;for(int i=0;i<s.Length;i++){char c=s[i];if(quote){if(c=='"'&&i+1<s.Length&&s[i+1]=='"'){cell.Append('"');i++;}else if(c=='"')quote=false;else cell.Append(c);}else if(c=='"')quote=true;else if(c==','){row.Add(cell.ToString());cell.Clear();}else if(c=='\r'){}else if(c=='\n'){row.Add(cell.ToString());cell.Clear();rows.Add(row);row=new List<string>();}else cell.Append(c);}if(quote)throw new InvalidDataException("CSV 引号未闭合。");if(cell.Length>0||row.Count>0){row.Add(cell.ToString());rows.Add(row);}if(rows.Count==0)return new List<VoiceTerm>();int wi=0,ai=-1,ei=-1,start=0;var head=rows[0].Select(x=>x.Trim().ToLowerInvariant()).ToList();if(head.Contains("word")){wi=head.IndexOf("word");ai=head.IndexOf("aliases");ei=head.IndexOf("enabled");start=1;}var list=new List<VoiceTerm>();for(int i=start;i<rows.Count;i++){var r=rows[i];string word=wi<r.Count?CsvImported(r[wi].Trim()):"";var aliases=ai>=0&&ai<r.Count?CsvImported(r[ai]).Split(new[]{'|',';'},StringSplitOptions.RemoveEmptyEntries).Select(x=>x.Trim()).ToList():new List<string>();var t=NewTerm(word,aliases,"import");if(ei>=0&&ei<r.Count){bool v;if(bool.TryParse(r[ei],out v))t.enabled=v;}list.Add(t);}return list;}
 public static void ExportCsv(string path,IEnumerable<VoiceTerm> terms){var b=new StringBuilder("word,aliases,enabled\r\n");foreach(var t in terms)b.Append(Csv(t.word)).Append(',').Append(Csv(string.Join("|",t.aliases??new List<string>()))).Append(',').Append(t.enabled?"true":"false").Append("\r\n");File.WriteAllText(path,b.ToString(),new UTF8Encoding(true));}
 static string Csv(string v){v=v??"";if(v.Length>0&&(v[0]=='='||v[0]=='+'||v[0]=='-'||v[0]=='@'))v="'"+v;return '"'+v.Replace("\"","\"\"")+'"';}
 static string CsvImported(string value){return value!=null&&value.Length>1&&value[0]=='\''&&(value[1]=='='||value[1]=='+'||value[1]=='-'||value[1]=='@')?value.Substring(1):value;}
 public static VoiceTerm NewTerm(string word,List<string> aliases,string source){string now=DateTime.UtcNow.ToString("o");return new VoiceTerm{word=word,aliases=aliases,source=source,createdAt=now,updatedAt=now};}
 static List<VoiceTerm> Validate(IEnumerable<VoiceTerm> input){var result=new List<VoiceTerm>();var seen=new HashSet<string>(StringComparer.Ordinal);foreach(var t in input){if(t==null)continue;t.word=(t.word??"").Trim();if(t.word.Length==0)continue;if(t.word.Length>100)throw new InvalidDataException("词语长度不能超过 100 个字符。");if(!seen.Add(t.word))continue;t.aliases=(t.aliases??new List<string>()).Where(x=>!string.IsNullOrWhiteSpace(x)).Select(x=>x.Trim()).Distinct(StringComparer.Ordinal).Take(20).ToList();if(string.IsNullOrEmpty(t.createdAt))t.createdAt=DateTime.UtcNow.ToString("o");t.updatedAt=DateTime.UtcNow.ToString("o");result.Add(t);if(result.Count>5000)throw new InvalidDataException("词库最多 5000 条。");}return result;}
 public static List<VoiceTerm> Merge(IEnumerable<VoiceTerm> current,IEnumerable<VoiceTerm> incoming){var all=Validate(current??new VoiceTerm[0]).ToDictionary(x=>x.word,StringComparer.Ordinal);foreach(var t in Validate(incoming)){VoiceTerm old;if(all.TryGetValue(t.word,out old)){old.aliases=(old.aliases??new List<string>()).Concat(t.aliases??new List<string>()).Distinct(StringComparer.Ordinal).Take(20).ToList();old.enabled=t.enabled;old.updatedAt=DateTime.UtcNow.ToString("o");}else{if(all.Count>=5000)throw new InvalidDataException("词库最多 5000 条。");all.Add(t.word,t);}}return Validate(all.Values).OrderBy(x=>x.word,StringComparer.CurrentCulture).ToList();}
 static void Atomic(string path,string text){Directory.CreateDirectory(Path.GetDirectoryName(path));string tmp=path+"."+Guid.NewGuid().ToString("N")+".tmp";File.WriteAllText(tmp,text,new UTF8Encoding(false));if(File.Exists(path)){string bak=path+".bak";File.Replace(tmp,path,bak,true);}else File.Move(tmp,path);}
}

sealed class DoubaoAsrClient:IDisposable {
 readonly VoiceOptions options;readonly List<string> hotwords;ClientWebSocket socket;CancellationTokenSource stop;Task receive;public event Action<string,bool> Text;public event Action<string> Failed;
 public DoubaoAsrClient(VoiceOptions o,IEnumerable<string> words){options=o;hotwords=words.Where(x=>!string.IsNullOrWhiteSpace(x)).Take(1000).ToList();}
 public async Task Connect(CancellationToken token){socket=new ClientWebSocket();if(!string.IsNullOrWhiteSpace(options.ApiKey))socket.Options.SetRequestHeader("X-Api-Key",options.ApiKey);else{socket.Options.SetRequestHeader("X-Api-App-Key",options.AppKey);socket.Options.SetRequestHeader("X-Api-Access-Key",options.AccessKey);}socket.Options.SetRequestHeader("X-Api-Resource-Id",options.ResourceId);socket.Options.SetRequestHeader("X-Api-Request-Id",Guid.NewGuid().ToString());socket.Options.SetRequestHeader("X-Api-Connect-Id",Guid.NewGuid().ToString());socket.Options.SetRequestHeader("X-Api-Sequence","-1");await socket.ConnectAsync(new Uri(options.Endpoint),token);stop=CancellationTokenSource.CreateLinkedTokenSource(token);receive=Receive(stop.Token);await SendRequest(stop.Token);}
 async Task SendRequest(CancellationToken t){var selected=new List<string>();int budget=0;foreach(var word in hotwords){int estimate=Math.Max(1,(word??"").Length);if(budget+estimate>80)break;selected.Add(word);budget+=estimate;}string context=new JavaScriptSerializer().Serialize(new Dictionary<string,object>{{"hotwords",selected.Select(x=>(object)new Dictionary<string,object>{{"word",x}}).ToArray()}});var request=new Dictionary<string,object>{{"model_name","bigmodel"},{"enable_itn",true},{"enable_punc",true},{"enable_ddc",false},{"enable_nonstream",true},{"show_utterances",true},{"corpus",new Dictionary<string,object>{{"context",context}}}};var req=new Dictionary<string,object>{{"user",new Dictionary<string,object>{{"uid",Environment.UserName}}},{"audio",new Dictionary<string,object>{{"format","pcm"},{"codec","raw"},{"rate",16000},{"bits",16},{"channel",1}}},{"request",request}};byte[] body=Gzip(Encoding.UTF8.GetBytes(new JavaScriptSerializer().Serialize(req)));await Send(Frame(0x10,0x11,body),t);}
 public Task SendAudio(byte[] pcm,bool final,CancellationToken t){return Send(Frame(final?(byte)0x22:(byte)0x20,0x01,Gzip(pcm)),t);}
 async Task Send(byte[] data,CancellationToken t){if(socket==null||socket.State!=WebSocketState.Open)throw new InvalidOperationException("识别连接未打开。");await socket.SendAsync(new ArraySegment<byte>(data),WebSocketMessageType.Binary,true,t);}
 async Task Receive(CancellationToken t){var buffer=new byte[65536];try{while(!t.IsCancellationRequested&&socket.State==WebSocketState.Open){using(var ms=new MemoryStream()){WebSocketReceiveResult r;do{r=await socket.ReceiveAsync(new ArraySegment<byte>(buffer),t);if(r.MessageType==WebSocketMessageType.Close)return;ms.Write(buffer,0,r.Count);}while(!r.EndOfMessage);Parse(ms.ToArray());}}}catch(OperationCanceledException){}catch(Exception e){if(Failed!=null)Failed(e.Message);}}
 void Parse(byte[] p){try{if(p==null||p.Length<4)throw new InvalidDataException("响应头不完整。");int header=(p[0]&15)*4,type=p[1]>>4,flags=p[1]&15,serial=p[2]>>4,compress=p[2]&15,offset=header;if(header<4||header>p.Length)throw new InvalidDataException("响应头长度无效。");if(type==0xf){if(p.Length<offset+8)throw new InvalidDataException("错误响应不完整。");int code=Read32(p,offset);offset+=4;int len=Read32(p,offset);offset+=4;if(len<0||offset+len>p.Length)throw new InvalidDataException("错误响应长度无效。");string error=Encoding.UTF8.GetString(Unzip(p,offset,len,compress));if(Failed!=null)Failed("ASR "+code+": "+error);return;}if(type!=0x9)throw new InvalidDataException("不支持的响应类型。");if((flags&1)!=0){if(p.Length<offset+4)throw new InvalidDataException("响应序号不完整。");offset+=4;}if(p.Length<offset+4)throw new InvalidDataException("响应长度字段不完整。");int size=Read32(p,offset);offset+=4;if(size<0||offset+size>p.Length)throw new InvalidDataException("响应负载长度无效。");string json=Encoding.UTF8.GetString(Unzip(p,offset,size,compress));var root=new JavaScriptSerializer().DeserializeObject(json) as Dictionary<string,object>;if(root==null)throw new InvalidDataException("响应不是 JSON 对象。");string value=ExtractText(root);bool final=(flags&2)!=0;if(Text!=null&&(final||!string.IsNullOrEmpty(value)))Text(value,final);}catch(Exception e){if(Failed!=null)Failed("识别响应无法解析："+e.Message);}}
 static string ExtractText(Dictionary<string,object> r){object result;if(r==null||!r.TryGetValue("result",out result)||result==null)return "";return ExtractResult(result);}
 static string ExtractResult(object result){var dict=result as Dictionary<string,object>;if(dict!=null){object text;if(dict.TryGetValue("text",out text)&&text!=null)return Convert.ToString(text);object utterances;if(dict.TryGetValue("utterances",out utterances)){var a=utterances as object[];if(a==null)throw new InvalidDataException("utterances 格式无效。");return string.Concat(a.Select(ExtractResult));}throw new InvalidDataException("result 缺少 text 或 utterances。");}var list=result as object[];if(list!=null)return string.Concat(list.Select(ExtractResult));throw new InvalidDataException("result 格式不受支持。");}
 static byte[] Frame(byte kind,byte codec,byte[] body){var p=new byte[8+body.Length];p[0]=0x11;p[1]=kind;p[2]=codec;p[3]=0;Write32(p,4,body.Length);Buffer.BlockCopy(body,0,p,8,body.Length);return p;}static byte[] Gzip(byte[] b){using(var o=new MemoryStream()){using(var z=new GZipStream(o,CompressionMode.Compress,true))z.Write(b,0,b.Length);return o.ToArray();}}static byte[] Unzip(byte[] b,int o,int n,int mode){if(mode!=1){var p=new byte[n];Buffer.BlockCopy(b,o,p,0,n);return p;}using(var i=new MemoryStream(b,o,n))using(var z=new GZipStream(i,CompressionMode.Decompress))using(var x=new MemoryStream()){z.CopyTo(x);return x.ToArray();}}
 static int Read32(byte[] b,int o){return (b[o]<<24)|(b[o+1]<<16)|(b[o+2]<<8)|b[o+3];}static void Write32(byte[] b,int o,int n){b[o]=(byte)(n>>24);b[o+1]=(byte)(n>>16);b[o+2]=(byte)(n>>8);b[o+3]=(byte)n;}
 public void Dispose(){if(stop!=null)stop.Cancel();if(socket!=null){socket.Dispose();socket=null;}if(stop!=null){stop.Dispose();stop=null;}}
}

static class VoiceCorrections {
 sealed class Rule {public string Alias,Word;public bool Ascii;}
 public static string Apply(string text,IEnumerable<VoiceTerm> terms){if(string.IsNullOrEmpty(text))return text;var ascii=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);var exact=new Dictionary<string,string>(StringComparer.Ordinal);var blockedAscii=new HashSet<string>(StringComparer.OrdinalIgnoreCase);var blockedExact=new HashSet<string>(StringComparer.Ordinal);foreach(var term in terms??new VoiceTerm[0]){if(term==null||!term.enabled)continue;foreach(var raw in term.aliases??new List<string>()){string alias=(raw??"").Trim();if(alias.Length==0||alias==term.word)continue;bool isAscii=alias.All(c=>c<128&&(char.IsLetterOrDigit(c)||c=='_'));var map=isAscii?ascii:exact;var blocked=isAscii?blockedAscii:blockedExact;string old;if(map.TryGetValue(alias,out old)&&old!=term.word)blocked.Add(alias);else map[alias]=term.word;}}foreach(string key in blockedAscii)ascii.Remove(key);foreach(string key in blockedExact)exact.Remove(key);var rules=ascii.Select(x=>new Rule{Alias=x.Key,Word=x.Value,Ascii=true}).Concat(exact.Select(x=>new Rule{Alias=x.Key,Word=x.Value})).OrderByDescending(x=>x.Alias.Length).ToList();var output=new StringBuilder(text.Length);for(int i=0;i<text.Length;){Rule hit=null;foreach(var rule in rules){if(i+rule.Alias.Length>text.Length)continue;var comparison=rule.Ascii?StringComparison.OrdinalIgnoreCase:StringComparison.Ordinal;if(!string.Equals(text.Substring(i,rule.Alias.Length),rule.Alias,comparison))continue;if(rule.Ascii&&((i>0&&AsciiWord(text[i-1]))||(i+rule.Alias.Length<text.Length&&AsciiWord(text[i+rule.Alias.Length]))))continue;hit=rule;break;}if(hit==null){output.Append(text[i]);i++;}else{output.Append(hit.Word);i+=hit.Alias.Length;}}return output.ToString();}
 static bool AsciiWord(char c){return c<128&&(char.IsLetterOrDigit(c)||c=='_');}
}

sealed class VoiceSession:IDisposable {
 internal const int MaxQueuedAudio=32,FlashTimeoutMilliseconds=60000;
 public VoiceState State {get;private set;}public string Preview {get;private set;}public string DeliveryStatus {get;private set;}public event Action<VoiceState,string,double> Changed;
 readonly VoiceOptions options;readonly List<VoiceTerm> terms;readonly object sync=new object();readonly SynchronizationContext ui;
 CancellationTokenSource cancel;DoubaoAsrClient client;WaveInput input;VoiceTarget target;Timer timeout;TaskCompletionSource<bool> finalResult;MemoryStream flashAudio;Task sendTail=Task.FromResult(0);
 int session,stopping,queuedAudio,queuedAudioGeneration,audioSeen,acceptingAudio,acceptingAudioGeneration,acceptingResults,failureSignaled,stopPending;bool delivered;
 public VoiceSession(VoiceOptions o,List<VoiceTerm> t){options=o;terms=t;var context=SynchronizationContext.Current;if(context==null&&Application.Current!=null)context=new System.Windows.Threading.DispatcherSynchronizationContext(Application.Current.Dispatcher);ui=context;State=VoiceState.Idle;}
 bool Current(int id){return Volatile.Read(ref session)==id;}
 void Post(Action action){if(ui!=null&&SynchronizationContext.Current!=ui)ui.Post(x=>action(),null);else action();}
 Task InvokeUi(Func<Task> action){if(ui==null||SynchronizationContext.Current==ui)return action();var completion=new TaskCompletionSource<bool>();ui.Post(async x=>{try{await action();completion.TrySetResult(true);}catch(Exception e){completion.TrySetException(e);}},null);return completion.Task;}
 void Change(VoiceState s,string text=null,double level=0){State=s;if(text!=null)Preview=text;if(s==VoiceState.Delivering)Preview=VoiceCorrections.Apply(Preview,terms);if(Changed!=null)Changed(s,Preview??"",level);}
 internal static async Task RequireFinal(Task final,int timeoutMilliseconds,CancellationToken token){if(final==null)throw new InvalidOperationException("最终识别结果任务不存在。");var completed=await Task.WhenAny(final,Task.Delay(timeoutMilliseconds,token));if(completed!=final)throw new TimeoutException("等待最终识别结果超时。");await final;}
 public Task Start(bool captureTarget){return InvokeUi(()=>StartOnUi(captureTarget));}
 async Task StartOnUi(bool captureTarget){
  if(State!=VoiceState.Idle)return;if(!options.Ready)throw new InvalidOperationException("请先填写豆包语音服务设置。");
  int id=Interlocked.Increment(ref session);Interlocked.Exchange(ref stopping,0);lock(sync){queuedAudio=0;queuedAudioGeneration=id;}Interlocked.Exchange(ref audioSeen,0);Interlocked.Exchange(ref acceptingAudio,0);Interlocked.Exchange(ref acceptingAudioGeneration,id);Interlocked.Exchange(ref acceptingResults,1);Interlocked.Exchange(ref failureSignaled,0);Interlocked.Exchange(ref stopPending,0);delivered=false;Preview="";DeliveryStatus="";sendTail=Task.FromResult(0);finalResult=new TaskCompletionSource<bool>();target=captureTarget?VoiceTarget.Capture():null;cancel=new CancellationTokenSource();Change(VoiceState.Starting);
  try{
   if(options.Backend=="stream"){
    client=new DoubaoAsrClient(options,terms.Where(x=>x.enabled).Select(x=>x.word));
    client.Text+=(text,final)=>Post(()=>{if(!Current(id)||Volatile.Read(ref acceptingResults)==0)return;if(!string.IsNullOrEmpty(text))Preview=text;Change(State,Preview);if(final&&finalResult!=null)finalResult.TrySetResult(true);});
    client.Failed+=e=>Fail(id,e);
    using(var connectTimeout=new CancellationTokenSource(12000))using(var linked=CancellationTokenSource.CreateLinkedTokenSource(cancel.Token,connectTimeout.Token))await client.Connect(linked.Token);
   }else flashAudio=new MemoryStream();
   if(!Current(id))return;input=new WaveInput();Interlocked.Exchange(ref acceptingAudio,1);input.Level+=v=>Post(()=>{if(Current(id))Change(State,null,v);});input.Data+=b=>OnAudio(id,b);input.Start();timeout=new Timer(x=>Post(async()=>await Stop()),null,TimeSpan.FromSeconds(Math.Max(10,Math.Min(300,options.MaxSeconds))),Timeout.InfiniteTimeSpan);Change(VoiceState.Listening);if(Volatile.Read(ref stopPending)!=0)await StopOnUi(id);
  }catch(Exception){if(Current(id)){CloseGeneration(id);Cleanup();Change(VoiceState.Idle);}throw;}
 }
 void OnAudio(int id,byte[] bytes){
  if(!Current(id)||Volatile.Read(ref acceptingAudio)==0||bytes==null||bytes.Length==0)return;Interlocked.Exchange(ref audioSeen,1);
  if(options.Backend!="stream"){lock(sync){if(Current(id)&&flashAudio!=null)flashAudio.Write(bytes,0,bytes.Length);}return;}
  Task next;CancellationToken token;DoubaoAsrClient activeClient;bool overflow=false;lock(sync){if(!Current(id)||queuedAudioGeneration!=id||cancel==null||client==null)return;if(++queuedAudio>MaxQueuedAudio){queuedAudio--;overflow=true;next=null;token=CancellationToken.None;activeClient=null;}else{token=cancel.Token;activeClient=client;next=SendAfter(sendTail,activeClient,bytes,token,id);sendTail=next;}}
  if(overflow){Fail(id,"语音网络发送过慢，请检查连接后重试。");return;}
  next.ContinueWith(t=>Fail(id,t.Exception.GetBaseException().Message),CancellationToken.None,TaskContinuationOptions.OnlyOnFaulted,TaskScheduler.Default);
 }
 async Task SendAfter(Task previous,DoubaoAsrClient activeClient,byte[] bytes,CancellationToken token,int id){try{await previous;if(Current(id)){token.ThrowIfCancellationRequested();await activeClient.SendAudio(bytes,false,token);}}finally{ReleaseQueuedAudio(id);}}
 void ReleaseQueuedAudio(int id){lock(sync){if(queuedAudioGeneration==id&&queuedAudio>0)queuedAudio--;}}
 void StopAcceptingAudio(int id){if(Current(id)&&Volatile.Read(ref acceptingAudioGeneration)==id)Interlocked.Exchange(ref acceptingAudio,0);}
 public Task Stop(){return InvokeUi(StopRequestedOnUi);}
 Task StopRequestedOnUi(){if(State==VoiceState.Starting){Interlocked.Exchange(ref stopPending,1);Interlocked.Exchange(ref stopping,1);return Task.FromResult(0);}if(State!=VoiceState.Listening||Interlocked.CompareExchange(ref stopping,1,0)!=0)return Task.FromResult(0);return StopOnUi(Volatile.Read(ref session));}
 async Task StopOnUi(int id){
  if(!Current(id))return;Change(VoiceState.Finalizing);var activeInput=input;input=null;
  try{
   if(activeInput!=null)await Task.Run(()=>{activeInput.StopAndDrain();activeInput.Dispose();});StopAcceptingAudio(id);if(!Current(id))return;
   if(Volatile.Read(ref audioSeen)==0){if(CloseGeneration(id)){Cleanup();Change(VoiceState.Idle,"");}return;}
   var sessionCancel=cancel;if(sessionCancel==null)throw new OperationCanceledException();
   if(options.Backend=="stream"){Task pending;Task final;DoubaoAsrClient activeClient;lock(sync){pending=sendTail;final=finalResult==null?null:finalResult.Task;activeClient=client;}await pending;EnsureDeliveryActive(id,sessionCancel.Token);await activeClient.SendAudio(new byte[0],true,sessionCancel.Token);EnsureDeliveryActive(id,sessionCancel.Token);await RequireFinal(final,10000,sessionCancel.Token);EnsureDeliveryActive(id,sessionCancel.Token);}
   else{byte[] pcm;lock(sync)pcm=flashAudio==null?new byte[0]:flashAudio.ToArray();try{using(var flashTimeout=new CancellationTokenSource(FlashTimeoutMilliseconds))using(var linked=CancellationTokenSource.CreateLinkedTokenSource(sessionCancel.Token,flashTimeout.Token))Preview=await new FlashAsrClient(options,terms.Where(x=>x.enabled).Select(x=>x.word).ToList()).Recognize(pcm,linked.Token);EnsureDeliveryActive(id,sessionCancel.Token);}catch(OperationCanceledException){if(!sessionCancel.IsCancellationRequested)throw new TimeoutException("豆包语音识别请求超时。");throw;}}
   EnsureDeliveryActive(id,sessionCancel.Token);if(string.IsNullOrWhiteSpace(Preview))throw new InvalidOperationException("没有识别到语音。");Interlocked.Exchange(ref acceptingResults,0);Change(VoiceState.Delivering);string finalText=Preview;VoiceTarget destination=target;bool pasted=await Deliver(id,destination,finalText,sessionCancel.Token);EnsureDeliveryActive(id,sessionCancel.Token);if(!CloseGeneration(id)||delivered)return;delivered=true;DeliveryStatus=pasted?"已输入并复制":"已复制，请手动粘贴";Cleanup();try{VoiceData.AddHistory(finalText,"final",options);}catch{DeliveryStatus+="；历史保存失败";}Change(VoiceState.Idle,finalText);
  }catch(FlashAsrException e){if(e.StatusCode=="20000003")FinishNoSpeech(id);else Fail(id,e.Message);}catch(OperationCanceledException){if(Current(id))Fail(id,"语音识别已取消。");}catch(Exception e){Fail(id,e.Message);}finally{if(activeInput!=null){try{activeInput.Dispose();}catch{}}StopAcceptingAudio(id);}
 }
 void EnsureDeliveryActive(int id,CancellationToken token){token.ThrowIfCancellationRequested();if(!Current(id))throw new OperationCanceledException();}
 async Task<bool> Deliver(int id,VoiceTarget destination,string text,CancellationToken token){
  EnsureDeliveryActive(id,token);if(ui!=null&&SynchronizationContext.Current!=ui){bool result=false;await InvokeUi(async()=>{result=await Deliver(id,destination,text,token);});EnsureDeliveryActive(id,token);return result;}
  bool pasted=destination!=null&&await destination.Paste(text,token);EnsureDeliveryActive(id,token);if(pasted)return true;for(int i=0;i<6;i++){EnsureDeliveryActive(id,token);bool retry=false;try{Clipboard.SetText(text);return false;}catch(COMException){retry=true;}if(retry&&i<5){await Task.Delay(80,token);EnsureDeliveryActive(id,token);}}throw new InvalidOperationException("剪贴板正被占用，未能自动粘贴。");
 }
 bool CloseGeneration(int id){return Interlocked.CompareExchange(ref session,id+1,id)==id;}
 void FinishNoSpeech(int id){Post(()=>{if(!CloseGeneration(id))return;Cleanup();DeliveryStatus="";Change(VoiceState.Idle,"没有识别到语音，请再试一次。");});}
 public void Cancel(){int id=Volatile.Read(ref session);Interlocked.CompareExchange(ref session,id+1,id);var activeCancel=cancel;if(activeCancel!=null)try{activeCancel.Cancel();}catch(ObjectDisposedException){}Post(()=>{Cleanup();Preview="";DeliveryStatus="";Change(VoiceState.Idle);});}
 void Fail(int id,string error){if(!Current(id)||Interlocked.CompareExchange(ref failureSignaled,1,0)!=0)return;Post(()=>FinishFailure(id,error));}
 void FinishFailure(int id,string error){if(!CloseGeneration(id))return;string draft=Preview;Cleanup();DeliveryStatus="";if(!string.IsNullOrWhiteSpace(draft))try{VoiceData.AddHistory(draft,"incomplete",options);}catch{error+="；未能保存未完成草稿";}Change(VoiceState.Error,error);Change(VoiceState.Idle,error);}
 void Cleanup(){Interlocked.Exchange(ref acceptingAudio,0);Interlocked.Exchange(ref acceptingAudioGeneration,0);Interlocked.Exchange(ref acceptingResults,0);if(timeout!=null){timeout.Dispose();timeout=null;}if(input!=null){try{input.Cancel();input.Dispose();}catch{}input=null;}if(cancel!=null){try{cancel.Cancel();}catch{}cancel.Dispose();cancel=null;}if(client!=null){client.Dispose();client=null;}lock(sync){if(flashAudio!=null){flashAudio.Dispose();flashAudio=null;}sendTail=Task.FromResult(0);queuedAudio=0;queuedAudioGeneration=0;}if(finalResult!=null){finalResult.TrySetCanceled();finalResult=null;}target=null;Interlocked.Exchange(ref stopping,0);}
 public void Dispose(){Cancel();}
}
