using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Web.Script.Serialization;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Interop;
using System.Windows.Media;

static class VoiceWindowNative {
 const int GwlExStyle=-20,WsExNoActivate=0x08000000,WsExToolWindow=0x00000080;
 [DllImport("user32.dll")] static extern int GetWindowLong(IntPtr window,int index);
 [DllImport("user32.dll")] static extern int SetWindowLong(IntPtr window,int index,int value);
 public static void MakeNoActivate(Window window){try{IntPtr handle=new WindowInteropHelper(window).Handle;int value=GetWindowLong(handle,GwlExStyle);SetWindowLong(handle,GwlExStyle,value|WsExNoActivate|WsExToolWindow);}catch{}}
}

sealed class VoiceHud : Window,IDisposable {
 readonly TextBlock stateText,timeText,transcript;readonly ProgressBar level;readonly Button cancelButton;bool disposing;
 public event Action CancelRequested;
 public VoiceHud(ResourceDictionary resources) {
  if(resources!=null)Resources=resources;Title="BanaStudio · 语音识别";Width=480;Height=164;WindowStyle=WindowStyle.None;ResizeMode=ResizeMode.NoResize;AllowsTransparency=false;Background=ColorBrush(1,255,255,255);Topmost=true;ShowInTaskbar=false;ShowActivated=false;Focusable=false;
  var shell=new Border{Background=ColorBrush(230,250,250,251),BorderBrush=ColorBrush(180,255,255,255),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(18),Padding=new Thickness(18,14,14,14)};
  var layout=new Grid();layout.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});layout.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});layout.RowDefinitions.Add(new RowDefinition{Height=new GridLength(1,GridUnitType.Star)});
  var head=new Grid();head.ColumnDefinitions.Add(new ColumnDefinition());head.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});stateText=new TextBlock{Text="准备就绪",FontSize=15,FontWeight=FontWeights.SemiBold,Foreground=Brush("#414145")};timeText=new TextBlock{Text="00:00",FontSize=12,Foreground=Brush("#777980"),VerticalAlignment=VerticalAlignment.Center};Grid.SetColumn(timeText,1);head.Children.Add(stateText);head.Children.Add(timeText);layout.Children.Add(head);
  level=new ProgressBar{Minimum=0,Maximum=1,Height=5,Margin=new Thickness(0,10,0,0),IsHitTestVisible=false};Grid.SetRow(level,1);layout.Children.Add(level);
  var body=new Grid{Margin=new Thickness(0,10,0,0)};body.ColumnDefinitions.Add(new ColumnDefinition());body.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(92)});transcript=new TextBlock{Text="按语音快捷键开始讲话",FontSize=13,Foreground=Brush("#55565B"),TextWrapping=TextWrapping.Wrap,MaxHeight=48,VerticalAlignment=VerticalAlignment.Center};cancelButton=new Button{Content="取消",Width=80,Height=38,IsEnabled=false,VerticalAlignment=VerticalAlignment.Center};cancelButton.Click+=(s,e)=>{var handler=CancelRequested;if(handler!=null)handler();};Grid.SetColumn(cancelButton,1);body.Children.Add(transcript);body.Children.Add(cancelButton);Grid.SetRow(body,2);layout.Children.Add(body);shell.Child=layout;Content=shell;
  SourceInitialized+=(s,e)=>{WindowBackdrop.Enable(this);OverlayNative.SetWindowDisplayAffinity(new WindowInteropHelper(this).Handle,0x11);VoiceWindowNative.MakeNoActivate(this);};
  Loaded+=(s,e)=>{Rect work=SystemParameters.WorkArea;Left=work.Left+(work.Width-Width)/2;Top=work.Bottom-Height-24;};
  Closing+=(s,e)=>{if(!disposing){e.Cancel=true;Hide();}};
 }
 static SolidColorBrush ColorBrush(byte a,byte r,byte g,byte b){return new SolidColorBrush(Color.FromArgb(a,r,g,b));}
 static Brush Brush(string value){return new SolidColorBrush((Color)ColorConverter.ConvertFromString(value));}
 public void Update(VoiceState state,string text,double volume,TimeSpan elapsed) {
  if(!Dispatcher.CheckAccess()){Dispatcher.BeginInvoke(new Action(()=>Update(state,text,volume,elapsed)));return;}
  string label;switch(state){case VoiceState.Starting:label="正在连接语音服务…";break;case VoiceState.Listening:label="正在听…";break;case VoiceState.Finalizing:label="正在完成识别…";break;case VoiceState.Delivering:label="正在输入…";break;case VoiceState.Error:label="识别失败";break;case VoiceState.Cancelled:label="已取消";break;default:label="准备就绪";break;}
  stateText.Text=label;stateText.Foreground=state==VoiceState.Error?Brush("#B3433D"):Brush("#414145");timeText.Text=elapsed.TotalHours>=1?elapsed.ToString(@"hh\:mm\:ss"):elapsed.ToString(@"mm\:ss");level.Value=Math.Max(0,Math.Min(1,volume));if(text!=null)transcript.Text=string.IsNullOrWhiteSpace(text)?(state==VoiceState.Finalizing?"正在等待最终文字…":"请开始讲话"):text;cancelButton.IsEnabled=state==VoiceState.Starting||state==VoiceState.Listening||state==VoiceState.Finalizing;
 }
 public void SetError(string message){Update(VoiceState.Error,message,0,TimeSpan.Zero);}
 public void Dispose(){if(disposing)return;disposing=true;Close();}
}

static class VoiceLibraryPersistence {
 static readonly JavaScriptSerializer Json=new JavaScriptSerializer{MaxJsonLength=4*1024*1024};
 public static void SaveHistory(IEnumerable<VoiceHistoryItem> items) {
  string path=Path.Combine(VoiceData.Root,"history.json");Directory.CreateDirectory(Path.GetDirectoryName(path));string temporary=path+"."+Guid.NewGuid().ToString("N")+".tmp";File.WriteAllText(temporary,Json.Serialize(items.ToList()),new UTF8Encoding(false));if(File.Exists(path))File.Replace(temporary,path,path+".bak",true);else File.Move(temporary,path);
 }
}

sealed class VoiceLibraryWindow : Window {
 List<VoiceTerm> terms;List<VoiceHistoryItem> history;readonly TextBox search,newWord,newAliases,wrongWord,correctWord;readonly StackPanel termRows,historyRows,correctionPanel;readonly TextBlock termSummary,historySummary,status;VoiceHistoryItem correctionItem;
 public event Action ImportRequested,ExportRequested;public event Action<List<VoiceTerm>> TermsChanged;public event Action<List<VoiceHistoryItem>> HistoryChanged;public event Action<string> CopyRequested;public event Action<string,string> CorrectionRemembered;
 public IList<VoiceTerm> Terms {get{return terms.AsReadOnly();}}public IList<VoiceHistoryItem> History {get{return history.AsReadOnly();}}
 public VoiceLibraryWindow(ResourceDictionary resources,List<VoiceTerm> terms,List<VoiceHistoryItem> history) {
  if(resources!=null)Resources=resources;this.terms=terms??new List<VoiceTerm>();this.history=history??new List<VoiceHistoryItem>();Title="BanaStudio · 词库与历史";Width=820;Height=650;MinWidth=700;MinHeight=520;WindowStartupLocation=WindowStartupLocation.CenterOwner;Background=Brush("#F7F7F9");
  var root=new Grid();root.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});root.RowDefinitions.Add(new RowDefinition());root.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});
  var header=new Grid{Margin=new Thickness(24,20,24,12)};header.ColumnDefinitions.Add(new ColumnDefinition());header.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});header.Children.Add(new TextBlock{Text="语音词库与历史",FontSize=22,FontWeight=FontWeights.SemiBold,VerticalAlignment=VerticalAlignment.Center});var close=new Button{Content="关闭",MinWidth=88};close.Click+=(s,e)=>Close();Grid.SetColumn(close,1);header.Children.Add(close);root.Children.Add(header);
  var tabs=new TabControl{Margin=new Thickness(24,0,24,12)};Grid.SetRow(tabs,1);root.Children.Add(tabs);
  var dictionary=new Grid{Margin=new Thickness(14)};dictionary.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});dictionary.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});dictionary.RowDefinitions.Add(new RowDefinition());dictionary.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});
  var tools=new Grid{Margin=new Thickness(0,0,0,10)};tools.ColumnDefinitions.Add(new ColumnDefinition());tools.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(100)});tools.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(100)});search=new TextBox{Height=36,Margin=new Thickness(0,3,10,0),ToolTip="搜索词语或别名"};search.TextChanged+=(s,e)=>RefreshTerms();var searchGroup=new StackPanel();searchGroup.Children.Add(new TextBlock{Text="搜索词语或别名",FontSize=11,Foreground=Brush("#66676C")});searchGroup.Children.Add(search);tools.Children.Add(searchGroup);var import=new Button{Content="导入",Margin=new Thickness(4,18,4,0)};import.Click+=(s,e)=>{var handler=ImportRequested;if(handler!=null)handler();};Grid.SetColumn(import,1);tools.Children.Add(import);var export=new Button{Content="导出",Margin=new Thickness(4,18,0,0)};export.Click+=(s,e)=>{var handler=ExportRequested;if(handler!=null)handler();};Grid.SetColumn(export,2);tools.Children.Add(export);dictionary.Children.Add(tools);
  termSummary=new TextBlock{Foreground=Brush("#777980"),FontSize=11,Margin=new Thickness(2,0,0,8)};Grid.SetRow(termSummary,1);dictionary.Children.Add(termSummary);termRows=new StackPanel();var termScroll=new ScrollViewer{Content=termRows,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};Grid.SetRow(termScroll,2);dictionary.Children.Add(termScroll);
  var add=new Grid{Margin=new Thickness(0,10,0,0)};add.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(180)});add.ColumnDefinitions.Add(new ColumnDefinition());add.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(92)});newWord=new TextBox{Height=36,Margin=new Thickness(0,3,8,0),ToolTip="正确词语"};newAliases=new TextBox{Height=36,Margin=new Thickness(0,3,8,0),ToolTip="常见误识别，用 | 分隔"};var wordGroup=new StackPanel();wordGroup.Children.Add(new TextBlock{Text="正确词语",FontSize=11,Foreground=Brush("#66676C")});wordGroup.Children.Add(newWord);var aliasGroup=new StackPanel();aliasGroup.Children.Add(new TextBlock{Text="常见误识别（可选）",FontSize=11,Foreground=Brush("#66676C")});aliasGroup.Children.Add(newAliases);var addButton=new Button{Content="添加",Height=36,Margin=new Thickness(0,18,0,0)};addButton.Click+=(s,e)=>AddTerm();add.Children.Add(wordGroup);Grid.SetColumn(aliasGroup,1);add.Children.Add(aliasGroup);Grid.SetColumn(addButton,2);add.Children.Add(addButton);Grid.SetRow(add,3);dictionary.Children.Add(add);tabs.Items.Add(new TabItem{Header="专有词库",Content=dictionary});
  var historyPage=new Grid{Margin=new Thickness(14)};historyPage.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});historyPage.RowDefinitions.Add(new RowDefinition());historyPage.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});var historyHead=new Grid{Margin=new Thickness(0,0,0,10)};historyHead.ColumnDefinitions.Add(new ColumnDefinition());historyHead.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(100)});historySummary=new TextBlock{Foreground=Brush("#777980"),VerticalAlignment=VerticalAlignment.Center};var clear=new Button{Content="清空历史"};clear.Click+=(s,e)=>ClearHistory();Grid.SetColumn(clear,1);historyHead.Children.Add(historySummary);historyHead.Children.Add(clear);historyPage.Children.Add(historyHead);historyRows=new StackPanel();var historyScroll=new ScrollViewer{Content=historyRows,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};Grid.SetRow(historyScroll,1);historyPage.Children.Add(historyScroll);
  correctionPanel=new StackPanel{Visibility=Visibility.Collapsed,Margin=new Thickness(0,10,0,0)};correctionPanel.Children.Add(new TextBlock{Text="纠错并记住",FontWeight=FontWeights.SemiBold,Margin=new Thickness(0,0,0,7)});var correction=new Grid();correction.ColumnDefinitions.Add(new ColumnDefinition());correction.ColumnDefinitions.Add(new ColumnDefinition());correction.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(110)});wrongWord=new TextBox{Height=36,Margin=new Thickness(0,3,8,0),ToolTip="错误词"};correctWord=new TextBox{Height=36,Margin=new Thickness(0,3,8,0),ToolTip="正确词"};var wrongGroup=new StackPanel();wrongGroup.Children.Add(new TextBlock{Text="错误词",FontSize=11,Foreground=Brush("#66676C")});wrongGroup.Children.Add(wrongWord);var correctGroup=new StackPanel();correctGroup.Children.Add(new TextBlock{Text="正确词",FontSize=11,Foreground=Brush("#66676C")});correctGroup.Children.Add(correctWord);var remember=new Button{Content="保存纠正",Height=36,Margin=new Thickness(0,18,0,0)};remember.Click+=(s,e)=>RememberCorrection();correction.Children.Add(wrongGroup);Grid.SetColumn(correctGroup,1);correction.Children.Add(correctGroup);Grid.SetColumn(remember,2);correction.Children.Add(remember);correctionPanel.Children.Add(correction);Grid.SetRow(correctionPanel,2);historyPage.Children.Add(correctionPanel);tabs.Items.Add(new TabItem{Header="转写历史",Content=historyPage});
  status=new TextBlock{Text="准备就绪",Foreground=Brush("#777980"),FontSize=11,Margin=new Thickness(26,0,26,16),TextTrimming=TextTrimming.CharacterEllipsis};Grid.SetRow(status,2);root.Children.Add(status);Content=root;SourceInitialized+=(s,e)=>WindowBackdrop.Enable(this);RefreshTerms();RefreshHistory();
 }
 static Brush Brush(string value){return new SolidColorBrush((Color)ColorConverter.ConvertFromString(value));}
 static List<string> ParseAliases(string text){return (text??"").Split(new[]{'|',';'},StringSplitOptions.RemoveEmptyEntries).Select(x=>x.Trim()).Where(x=>x.Length>0).Distinct(StringComparer.Ordinal).Take(20).ToList();}
 Border Card(UIElement child){return new Border{Child=child,Background=Brush("#FFFFFFFF"),BorderBrush=Brush("#E4E4E8"),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(10),Padding=new Thickness(10),Margin=new Thickness(0,0,0,8)};}
 void SetStatus(string value){status.Text=value;}
 void SaveTerms(string message){VoiceData.SaveTerms(terms);RefreshTerms();var handler=TermsChanged;if(handler!=null)handler(terms);SetStatus(message);}
 void SaveHistory(string message){VoiceLibraryPersistence.SaveHistory(history);RefreshHistory();var handler=HistoryChanged;if(handler!=null)handler(history);SetStatus(message);}
 public void MergeImported(IEnumerable<VoiceTerm> incoming){terms=VoiceData.Merge(terms,incoming??new VoiceTerm[0]);SaveTerms("词库已合并导入");}
 public void ReplaceHistory(IEnumerable<VoiceHistoryItem> values){history=(values??new VoiceHistoryItem[0]).ToList();RefreshHistory();}
 void AddTerm(){string word=(newWord.Text??"").Trim();if(word.Length==0){SetStatus("请输入正确词语");return;}if(word.Length>100){SetStatus("词语长度不能超过 100 个字符");return;}if(terms.Any(x=>string.Equals(x.word,word,StringComparison.Ordinal))){SetStatus("词库中已有这个词");return;}terms.Add(VoiceData.NewTerm(word,ParseAliases(newAliases.Text),"manual"));newWord.Clear();newAliases.Clear();SaveTerms("已添加专有词");}
 void RefreshTerms(){if(termRows==null)return;termRows.Children.Clear();string query=(search.Text??"").Trim();var shown=terms.Where(x=>query.Length==0||(x.word??"").IndexOf(query,StringComparison.CurrentCultureIgnoreCase)>=0||(x.aliases??new List<string>()).Any(a=>(a??"").IndexOf(query,StringComparison.CurrentCultureIgnoreCase)>=0)).OrderBy(x=>x.word,StringComparer.CurrentCulture).Take(500).ToList();termSummary.Text="搜索词语或别名 · 列：正确词语 / 常见误识别（可选） · "+terms.Count(x=>x.enabled)+" 个启用 · "+terms.Count+" 个词"+(shown.Count<terms.Count?" · 当前显示前 "+shown.Count+" 个":"");foreach(var term in shown)termRows.Children.Add(TermRow(term));}
 UIElement TermRow(VoiceTerm term){var grid=new Grid();grid.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(44)});grid.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(170)});grid.ColumnDefinitions.Add(new ColumnDefinition());grid.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(72)});grid.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(72)});var enabled=new CheckBox{IsChecked=term.enabled,VerticalAlignment=VerticalAlignment.Center,HorizontalAlignment=HorizontalAlignment.Center,ToolTip="启用"};var word=new TextBox{Text=term.word,Height=34,Margin=new Thickness(4,0,6,0)};var aliases=new TextBox{Text=string.Join("|",term.aliases??new List<string>()),Height=34,Margin=new Thickness(0,0,6,0),ToolTip="常见误识别，用 | 分隔"};var save=new Button{Content="保存",Margin=new Thickness(2,0,2,0)};var remove=new Button{Content="删除",Margin=new Thickness(2,0,0,0)};enabled.Checked+=(s,e)=>{term.enabled=true;SaveTerms("已启用 "+term.word);};enabled.Unchecked+=(s,e)=>{term.enabled=false;SaveTerms("已停用 "+term.word);};save.Click+=(s,e)=>{string value=(word.Text??"").Trim();if(value.Length==0||value.Length>100){SetStatus("词语不能为空且不能超过 100 个字符");return;}if(terms.Any(x=>!ReferenceEquals(x,term)&&string.Equals(x.word,value,StringComparison.Ordinal))){SetStatus("词库中已有这个词");return;}term.word=value;term.aliases=ParseAliases(aliases.Text);term.updatedAt=DateTime.UtcNow.ToString("o");SaveTerms("已保存词语");};remove.Click+=(s,e)=>{terms.Remove(term);SaveTerms("已删除词语");};grid.Children.Add(enabled);Grid.SetColumn(word,1);grid.Children.Add(word);Grid.SetColumn(aliases,2);grid.Children.Add(aliases);Grid.SetColumn(save,3);grid.Children.Add(save);Grid.SetColumn(remove,4);grid.Children.Add(remove);return Card(grid);}
 void RefreshHistory(){if(historyRows==null)return;historyRows.Children.Clear();historySummary.Text=history.Count+" 条本地转写";foreach(var item in history.OrderByDescending(x=>x.createdAt).Take(500))historyRows.Children.Add(HistoryRow(item));}
 UIElement HistoryRow(VoiceHistoryItem item){var layout=new Grid();layout.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});layout.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});var meta=new TextBlock{Text=HistoryTime(item.createdAt)+" · "+(item.status=="final"?"已完成":"未完成草稿"),FontSize=11,Foreground=Brush("#777980")};layout.Children.Add(meta);var row=new Grid{Margin=new Thickness(0,7,0,0)};row.ColumnDefinitions.Add(new ColumnDefinition());row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(66)});row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(108)});row.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(66)});var text=new TextBlock{Text=item.text??"",TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,4,8,4)};var copy=new Button{Content="复制",Margin=new Thickness(2,0,2,0)};var correct=new Button{Content="纠错并记住",Margin=new Thickness(2,0,2,0)};var remove=new Button{Content="删除",Margin=new Thickness(2,0,0,0)};copy.Click+=(s,e)=>Copy(item.text);correct.Click+=(s,e)=>BeginCorrection(item);remove.Click+=(s,e)=>{history.Remove(item);SaveHistory("已删除历史");};row.Children.Add(text);Grid.SetColumn(copy,1);row.Children.Add(copy);Grid.SetColumn(correct,2);row.Children.Add(correct);Grid.SetColumn(remove,3);row.Children.Add(remove);Grid.SetRow(row,1);layout.Children.Add(row);return Card(layout);}
 static string HistoryTime(string value){DateTime parsed;return DateTime.TryParse(value,out parsed)?parsed.ToLocalTime().ToString("yyyy-MM-dd HH:mm"):"时间未知";}
 void Copy(string value){if(string.IsNullOrEmpty(value))return;var handler=CopyRequested;if(handler!=null){handler(value);SetStatus("已请求复制");return;}try{Clipboard.SetText(value);SetStatus("已复制到剪贴板");}catch{SetStatus("剪贴板正被占用，请稍后重试");}}
 void ClearHistory(){history.Clear();VoiceData.ClearHistory();RefreshHistory();var handler=HistoryChanged;if(handler!=null)handler(history);SetStatus("历史已清空");}
 void BeginCorrection(VoiceHistoryItem item){correctionItem=item;wrongWord.Clear();correctWord.Clear();correctionPanel.Visibility=Visibility.Visible;wrongWord.Focus();SetStatus("输入错误词和正确词，保存后会加入词库");}
 void RememberCorrection(){if(correctionItem==null)return;string wrong=(wrongWord.Text??"").Trim(),correct=(correctWord.Text??"").Trim();if(wrong.Length==0||correct.Length==0){SetStatus("错误词和正确词都不能为空");return;}if(correct.Length>100){SetStatus("正确词不能超过 100 个字符");return;}var term=terms.FirstOrDefault(x=>string.Equals(x.word,correct,StringComparison.Ordinal));if(term==null){term=VoiceData.NewTerm(correct,new List<string>{wrong},"correction");terms.Add(term);}else{term.aliases=(term.aliases??new List<string>()).Concat(new[]{wrong}).Where(x=>!string.IsNullOrWhiteSpace(x)).Distinct(StringComparer.Ordinal).Take(20).ToList();term.enabled=true;term.updatedAt=DateTime.UtcNow.ToString("o");}if(!string.IsNullOrEmpty(correctionItem.text))correctionItem.text=correctionItem.text.Replace(wrong,correct);VoiceData.SaveTerms(terms);VoiceLibraryPersistence.SaveHistory(history);RefreshTerms();RefreshHistory();correctionPanel.Visibility=Visibility.Collapsed;var termsHandler=TermsChanged;if(termsHandler!=null)termsHandler(terms);var historyHandler=HistoryChanged;if(historyHandler!=null)historyHandler(history);var correctionHandler=CorrectionRemembered;if(correctionHandler!=null)correctionHandler(wrong,correct);SetStatus("已纠正，并把正确词加入热词词库");}
}
